# Generated by Django 5.0.4 on 2024-06-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model1', '0002_alter_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
