# Generated by Django 5.0.4 on 2024-07-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model1', '0004_car_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='speed',
            field=models.IntegerField(default=120),
        ),
    ]
